const comics = [
  {
    title: "Watchmen",
    type: "novela gráfica",
    year: 1986,
    creators: ["Alan Moore", "Dave Gibbons"],
    publisher: "DC Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781401245252-L.jpg",
  },
  {
    title: "Batman: The Dark Knight Returns",
    type: "miniserie / novela gráfica",
    year: 1986,
    creators: ["Frank Miller", "Klaus Janson", "Lynn Varley"],
    publisher: "DC Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781401263119-L.jpg",
  },
  {
    title: "Maus",
    type: "novela gráfica",
    year: 1980,
    creators: ["Art Spiegelman"],
    publisher: "Pantheon Books",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780679406419-L.jpg",
  },
  {
    title: "The Sandman: Preludes & Nocturnes",
    type: "serie / novela gráfica",
    year: 1989,
    creators: ["Neil Gaiman", "Sam Kieth", "Mike Dringenberg"],
    publisher: "DC Comics / Vertigo",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781401225759-L.jpg",
  },
  {
    title: "V for Vendetta",
    type: "novela gráfica",
    year: 1982,
    creators: ["Alan Moore", "David Lloyd"],
    publisher: "DC Comics / Vertigo",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781401208417-L.jpg",
  },
  {
    title: "Batman: Year One",
    type: "arco argumental",
    year: 1987,
    creators: ["Frank Miller", "David Mazzucchelli"],
    publisher: "DC Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781401207526-L.jpg",
  },
  {
    title: "Batman: The Killing Joke",
    type: "novela gráfica",
    year: 1988,
    creators: ["Alan Moore", "Brian Bolland"],
    publisher: "DC Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781401216672-L.jpg",
  },
  {
    title: "The Amazing Spider-Man: Omnibus Vol. 1",
    type: "serie recopilada",
    year: 1963,
    creators: ["Stan Lee", "Steve Ditko"],
    publisher: "Marvel Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780785124023-L.jpg",
  },
  {
    title: "X-Men: The Dark Phoenix Saga",
    type: "arco argumental",
    year: 1980,
    creators: ["Chris Claremont", "John Byrne"],
    publisher: "Marvel Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780785122135-L.jpg",
  },
  {
    title: "The Infinity Gauntlet",
    type: "miniserie",
    year: 1991,
    creators: ["Jim Starlin", "George Pérez", "Ron Lim"],
    publisher: "Marvel Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780785156598-L.jpg",
  },
  {
    title: "Civil War",
    type: "evento",
    year: 2006,
    creators: ["Mark Millar", "Steve McNiven"],
    publisher: "Marvel Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780785121794-L.jpg",
  },
  {
    title: "The Walking Dead: Days Gone Bye",
    type: "serie / volumen 1",
    year: 2003,
    creators: ["Robert Kirkman", "Tony Moore"],
    publisher: "Image Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781582406725-L.jpg",
  },
  {
    title: "Saga: Volume One",
    type: "serie / volumen 1",
    year: 2012,
    creators: ["Brian K. Vaughan", "Fiona Staples"],
    publisher: "Image Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781607066019-L.jpg",
  },
  {
    title: "Spawn: Origins Collection Vol. 1",
    type: "serie recopilada",
    year: 1992,
    creators: ["Todd McFarlane"],
    publisher: "Image Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781607060710-L.jpg",
  },
  {
    title: "Hellboy: Seed of Destruction",
    type: "serie / volumen 1",
    year: 1994,
    creators: ["Mike Mignola", "John Byrne"],
    publisher: "Dark Horse Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781593070946-L.jpg",
  },
  {
    title: "Sin City: The Hard Goodbye",
    type: "serie / volumen 1",
    year: 1991,
    creators: ["Frank Miller"],
    publisher: "Dark Horse Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781593072933-L.jpg",
  },
  {
    title: "300",
    type: "novela gráfica",
    year: 1998,
    creators: ["Frank Miller", "Lynn Varley"],
    publisher: "Dark Horse Comics",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781569714027-L.jpg",
  },
  {
    title: "Persepolis",
    type: "novela gráfica autobiográfica",
    year: 2000,
    creators: ["Marjane Satrapi"],
    publisher: "L'Association / Pantheon Books",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780375714573-L.jpg",
  },
  {
    title: "Asterix the Gaul",
    type: "cómic europeo / álbum",
    year: 1959,
    creators: ["René Goscinny", "Albert Uderzo"],
    publisher: "Dargaud",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780752866055-L.jpg",
  },
  {
    title: "Tintin in the Land of the Soviets",
    type: "cómic europeo / álbum",
    year: 1929,
    creators: ["Hergé"],
    publisher: "Casterman",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780316003742-L.jpg",
  },
  {
    title: "One Piece Vol. 1",
    type: "manga / volumen 1",
    year: 1997,
    creators: ["Eiichiro Oda"],
    publisher: "Shueisha / Viz Media",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781569319017-L.jpg",
  },
  {
    title: "Dragon Ball Vol. 1",
    type: "manga / volumen 1",
    year: 1984,
    creators: ["Akira Toriyama"],
    publisher: "Shueisha / Viz Media",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781569319208-L.jpg",
  },
  {
    title: "Naruto Vol. 1",
    type: "manga / volumen 1",
    year: 1999,
    creators: ["Masashi Kishimoto"],
    publisher: "Shueisha / Viz Media",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781569319000-L.jpg",
  },
  {
    title: "Bleach Vol. 1",
    type: "manga / volumen 1",
    year: 2001,
    creators: ["Tite Kubo"],
    publisher: "Shueisha / Viz Media",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781591164418-L.jpg",
  },
  {
    title: "Death Note Vol. 1",
    type: "manga / volumen 1",
    year: 2003,
    creators: ["Tsugumi Ohba", "Takeshi Obata"],
    publisher: "Shueisha / Viz Media",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781421501680-L.jpg",
  },
  {
    title: "Akira Vol. 1",
    type: "manga / volumen 1",
    year: 1982,
    creators: ["Katsuhiro Otomo"],
    publisher: "Kodansha",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781935429005-L.jpg",
  },
  {
    title: "Berserk Vol. 1",
    type: "manga / volumen 1",
    year: 1989,
    creators: ["Kentaro Miura"],
    publisher: "Hakusensha / Dark Horse Manga",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781593070205-L.jpg",
  },
  {
    title: "Fullmetal Alchemist Vol. 1",
    type: "manga / volumen 1",
    year: 2001,
    creators: ["Hiromu Arakawa"],
    publisher: "Square Enix / Viz Media",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781591169208-L.jpg",
  },
  
];

for (const comic of comics) {
  const li = document.createElement("li");
  li.innerHTML = `
    <img src="${comic.coverUrl}" alt="${comic.title}"/>
    <h2>${comic.title}</h2>
    <p>${comic.year} - ${comic.creators[0]}</p>
    <p>${comic.publisher}</p>
    `;

  document.querySelector("#contenedor_comics").appendChild(li);
}
